--liquibase generateChangeLog --changeLogFile=baseline.sql

-- liquibase formatted sql

-- changeset benriley:1787141272151-1 splitStatements:false
CREATE TABLE "audit_log" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "action" VARCHAR(100), "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id"));

-- changeset benriley:1787141272151-2 splitStatements:false
CREATE TABLE "rental_history" ("rental_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL, "customer_id" INTEGER, "rental_date" date, "return_date" date, "rental_amount" numeric(10, 2), "priority_flag" BOOLEAN DEFAULT FALSE, CONSTRAINT "rental_history_pkey" PRIMARY KEY ("rental_id"));

-- changeset benriley:1787141272151-3 splitStatements:false
CREATE TABLE "addresses" ("address_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL, "customer_id" INTEGER, "address_line1" VARCHAR(100), "address_line2" VARCHAR(100), "city" VARCHAR(50), "state" VARCHAR(50), "zip_code" VARCHAR(20), CONSTRAINT "addresses_pkey" PRIMARY KEY ("address_id"));

-- changeset benriley:1787141272151-4 splitStatements:false
CREATE TABLE "customers" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(30), CONSTRAINT "customers_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1787141272151-5 splitStatements:false
CREATE INDEX "idx_customer_email" ON "customers" USING btree("email");

-- changeset benriley:1787141272151-6 splitStatements:false
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset benriley:1787141272151-7 splitStatements:false
ALTER TABLE "rental_history" ADD CONSTRAINT "rental_history_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

