stages:
  Rollback:
    actions:
      - type: liquibase
        command: rollbackOneUpdate
        cmdArgs: { force: "true" }
        globalArgs: { report-enabled: "true", reports-open: "false", report-path: "reports/", report-name: "rollback-report.html" }