stages:
  Status:
    actions:
      - type: liquibase
        command: status
        cmdArgs: { verbose: true }

  PolicyChecks:
    actions:
      - type: liquibase
        command: checks run
        globalArgs: { report-enabled: true, reports-open: "false", report-path: "reports/", report-name: "policy-checks-report.html" }

  DriftDetection:
    actions:
      - type: liquibase
        command: diff
        cmdArgs: { referenceUrl: "offline:postgresql?snapshot=snapshots/reference.json" }
        globalArgs: { report-enabled: true, reports-open: "false", report-path: "reports/", report-name: "drift-report.html" }