##########           LIQUIBASE FLOWFILE - ROLLBACK BY DEPLOYMENT ID    ##########
##########  learn more http://docs.liquibase.com/flow                  ##########

## USAGE:
## export LIQUIBASE_COMMAND_DEPLOYMENT_ID=0654688620
## liquibase flow --flow-file=flowfile.rollback.yaml
## Or trigger via Jenkins with DEPLOYMENT_ID parameter.

stages:

  Default:

    actions:
      - type: liquibase
        command: rollback-one-update
        cmdArgs:
          force: "true"
          deployment-id: "${LIQUIBASE_COMMAND_DEPLOYMENT_ID}"

endStage:
  actions:
    - type: liquibase
      command: history