stages:
  Deploy:
    actions:
      - type: liquibase
        command: update
        globalArgs: { report-enabled: true, reports-open: "false", report-path: "reports/", report-name: "deploy-report.html" }