stages:
  Validate:
    actions:
      - type: liquibase
        command: validate

  StatusCheck:
    actions:
      - type: liquibase
        command: status
        cmdArgs:
          verbose: true

  Deploy:
    actions:
      - type: liquibase
        command: update