####     _     _             _ _
##      | |   (_)           (_) |
##      | |    _  __ _ _   _ _| |__   __ _ ___  ___
##      | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \
##      | |___| | (_| | |_| | | |_) | (_| \__ \  __/
##      \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|
##                  | |
##                  |_|
##
##      The liquibase.properties file stores properties which do not change often,
##      such as database connection information. Properties stored here save time
##      and reduce risk of mistyped command line arguments.
##      Learn more: https://docs.liquibase.com/concepts/connections/creating-config-properties.html
####
changeLogFile=changelog/master.xml
searchPath=.

# Enable Liquibase Pro license key from Vault
liquibase.licenseKey=hashicorp,secret/data/liquibase/license,pro_key

# # Database connection details retrieved from Vault
liquibase.command.url=jdbc:postgresql://localhost:5433/postgres
liquibase.command.username=hashicorp,secret/data/liquibase/credentials,username
liquibase.command.password=hashicorp,secret/data/liquibase/credentials,password

# # Reference database (QA) details retrieved from Vault
liquibase.command.referenceUrl=jdbc:postgresql://localhost:5434/postgres
liquibase.command.referenceUsername=hashicorp,secret/data/liquibase/credentials,username
liquibase.command.referencePassword=hashicorp,secret/data/liquibase/credentials,password

# Vault connection details
vault.addr=http://localhost:8200
vault.token=vault-plaintext-root-token

# Enable Liquibase change log history
liquibase.dbclhistory.enabled=true 
liquibase.dbclhistory.file=liquibase.dbclhistory  

# Logging
liquibase.logFormat=JSON
liquibase.logFile=liquibase.json
liquibase.logLevel=INFO

liquibase.command.checksScriptsEnabled=true

# Liquibase Pro license key
liquibase.licenseKey=hashicorp,secret/data/liquibase/license,pro_key
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Get support at liquibase.com/support         ##

