####     _     _             _ _
##      | |   (_)           (_) |
##      | |    _  __ _ _   _ _| |__   __ _ ___  ___
##      | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \
##      | |___| | (_| | |_| | | |_) | (_| \__ \  __/
##      \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|
##                  | |
##                  |_|
##
##      The liquibase.properties file stores properties which do not change often,
##      such as database connection information. Properties stored here save time
##      and reduce risk of mistyped command line arguments.
##      Learn more: https://docs.liquibase.com/concepts/connections/creating-config-properties.html
####

changeLogFile=changelog/main.root.xml
searchPath=.
#DevDB
url=jdbc:postgresql://localhost:5433/postgres
username=postgres
password=secret


# # Reference database (QA) details retrieved from Vault
liquibase.command.referenceUrl=jdbc:postgresql://localhost:5434/postgres
liquibase.command.referenceUsername=hashicorp,secret/data/liquibase/credentials,username
liquibase.command.referencePassword=hashicorp,secret/data/liquibase/credentials,password

# Vault connection details
vault.addr=http://localhost:8200
vault.token=vault-plaintext-root-token

# Enable Liquibase change log history
liquibase.dbclhistory.enabled=true 
liquibase.dbclhistory.file=liquibase.dbclhistory  

# Logging
liquibase.logFormat=JSON
liquibase.logFile=liquibase.json
liquibase.logLevel=INFO

liquibase.command.checksScriptsEnabled=true

# Liquibase Secure license key
liquibase.licenseKey=hashicorp,secret/data/liquibase/license,pro_key

##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Get support at liquibase.com/support         ##



export LIQUIBASE_LICENSE_KEY="ABwwGgQUPh6hG63DdAv4KU7uB9ZHepGOr1sCAgQA5IFGkcY9U/u/JYd+RJt6vlqo/D7zmioDsJROmy/hs1fOnEq32TI2d/1Q7jyCilaoEH6McuUGFa9Bm/UmSRqWADisnvxIeof2i3EgMTSiL4pUA9sk3i5XeqEDGmwoqQMLIzq54NpPzrMzsONXXo3Uw7pDb3Xkh1WKmoeUY2JuClWH8BslO6xtWBLAbSzCn2z027f19EdtwQbsK/xzI1uakeq53fPZUKXw8PkcnqH/yFlQ/VGfswNoR5qyb8+rM2gDHfIL58H21JJ4A4HI6dTdlsJDWbMyahj0ipdXz0Ms5WzbzxYWRmk/jemjK2q4qwrwNj4hfrjhnxLRd4GO6E2qOJ0cymYOhODLX8utXTUy9+MSuhm/Ph4ndqU5rVzkfTxIk36+Q41gmotSa09mNeUJZk8QeJthsaeC2p5XVhOYvYzpxG4jG/Rzhqauw/4bmiCAHYPxSUI/segjWctQKx3wHAQN0/qzByHz7gt7VAKZ9DEp8k2LS4Vfrwxz7gOGLqD8Apn9snM1kWUZTmlCp9ELV7xuspA/Nd3iCCU7B44xFZ41j05/gAKDR9qdanBeVZR5ZqZS/aCLjNn3Y81OY4EuY5kltKU93Kchx+Ii7e6gA0d+xWm0opiGykFL/cUDvg8Ymu4YrGZ3ztZzQcjoWECELLeIYEvjyPb7ZwrmfCK1+Ss="
java -jar liquibase-mcp-changelog-server-0.1.0-SNAPSHOT.jar



##liq_SLjRebYMWdEbzoeCNMGBxzmFyYTJAZTnygbEcBdIYCVuceeUeUFaAdGxKCquWvDU - CI
